---
title: "startups"
author: "Group 7"
date: "26/11/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(skimr)
library(vroom)
library(tidyverse) # the usual stuff: dplyr, readr, and other goodies
library(lubridate) # to handle dates
library(GGally) # for correlation-scatter plot matrix
library(ggfortify) # to produce residual diagnostic plots
library(rsample) # to split dataframe in training- & testing sets
library(janitor) # clean_names()
library(broom) # use broom:augment() to get tidy table with regression output, residuals, etc
library(huxtable) # to get summary table of all models produced
library(caret) # to train more advanced models (k-fold cross-validation, stepwise regression, LASSO)
library(nnet) # to calculate the maximum value of a vector
library(pROC) # to plot ROC curves
library(MLmetrics) #for caret LASSO logistic regression
library(stringr)
library(RTextTools)
library(SnowballC)
library(wordcloud)
library(tm)
library(ggplot2)
library(tmap)
library(tmaptools)
library(sf)
library(maps)
```

# Stage of funding
```{r}
data_startups_original <- "STARTUPS"
files <- fs::dir_ls(path = data_startups_original, regexp = "\\.csv$", recurse = TRUE) 
startups_data <- vroom(files, id = "source")
write.csv(x = startups_data,file = "startups_data.csv")

data_investors_original <- "INVESTORS"
files <- fs::dir_ls(path = data_investors_original, regexp = "\\.csv$", recurse = TRUE) 
investors_data <- vroom(files, id = "source")
write.csv(x = investors_data,file = "investors_data.csv")
```

```{r}
startups_data <- startups_data %>% clean_names()
skim(startups_data)
```


```{r}
startups_data %>%
  select(transaction_name, organization_name, number_of_investors, money_raised_currency_in_usd, total_funding_amount_currency_in_usd)%>%
  glimpse()
```

```{r}
relevant_for_funding_stages <- startups_data %>% select(money_raised_currency_in_usd,transaction_name,funding_type, funding_status, funding_stage, money_raised_currency_in_usd, number_of_funding_rounds, pre_money_valuation_currency_in_usd, total_funding_amount_currency_in_usd, number_of_investors)
glimpse(relevant_for_funding_stages)
```
```{r}
relevant_for_funding_stages %>%
  select(funding_type)%>%
  group_by(funding_type)%>%
  summarise(count = n())

relevant_for_funding_stages %>%
  select(funding_status)%>%
  group_by(funding_status)%>%
  summarise(count = n())

relevant_for_funding_stages %>%
  select(funding_stage)%>%
  group_by(funding_stage)%>%
  summarise(count = n())
```

```{r}
relevant_for_funding_stages %>%
  filter(!is.na(funding_type))%>%
  filter(!is.na(money_raised_currency_in_usd))%>%
  group_by(funding_type)%>%
  summarise(funding = sum(money_raised_currency_in_usd))%>%
  ggplot(aes(y = funding_type, x = funding))+
  geom_col()+
  theme_classic()+
  NULL

relevant_for_funding_stages %>%
  filter(!is.na(funding_type))%>%
  group_by(funding_type)%>%
  summarise(count = n())%>%
  ggplot(aes(y = funding_type, x = count))+
  geom_col()+
  theme_classic()+
  NULL

relevant_for_funding_stages %>%
  filter(!is.na(funding_type))%>%
  filter(!is.na(money_raised_currency_in_usd))%>%
  group_by(funding_type)%>%
  summarise(funding = sum(money_raised_currency_in_usd), number = n())%>%
  mutate(average_funding = funding/number)%>%
  ggplot(aes(y = fct_reorder(funding_type,average_funding), x = average_funding, fill = fct_reorder(funding_type,average_funding)))+
  geom_col()+
  theme_classic()+
  scale_fill_discrete(h = c(100, 235) + 15, c = 100, l = 65, h.start = 0, direction = 1)+
  labs(title = "Average funding per funding type", subtitle = "", x = "Funding in USD", y = "Funding type")+
  theme(legend.position = "none")+
  NULL
  
```

```{r}
relevant_for_funding_stages %>%
  filter(!is.na(funding_stage))%>%
  filter(!is.na(money_raised_currency_in_usd))%>%
  group_by(funding_stage)%>%
  summarise(funding = sum(money_raised_currency_in_usd))%>%
  ggplot(aes(x = funding_stage, y = funding))+
  geom_col()

relevant_for_funding_stages %>%
  filter(!is.na(funding_stage))%>%
  group_by(funding_stage)%>%
  summarise(count = n())%>%
  ggplot(aes(x = funding_stage, y = count))+
  geom_col()

relevant_for_funding_stages %>%
  filter(!is.na(funding_stage))%>%
  filter(!is.na(money_raised_currency_in_usd))%>%
  group_by(funding_stage)%>%
  summarise(funding = sum(money_raised_currency_in_usd), number = n())%>%
  mutate(average_funding = funding/number)%>%
  ggplot(aes(x = fct_reorder(funding_stage,average_funding), y = average_funding))+
  geom_col()
```


```{r}
relevant_for_funding_stages %>%
  filter(!is.na(number_of_funding_rounds))%>%
  group_by(number_of_funding_rounds)%>%
  summarise(number = n())%>%
  ggplot(aes(x =number_of_funding_rounds, y = number))+
  geom_col()
```

```{r}
relevant_for_funding_stages %>%
  filter(!is.na(pre_money_valuation_currency_in_usd))%>%
  filter(!is.na(total_funding_amount_currency_in_usd))%>%
  ggplot(aes(total_funding_amount_currency_in_usd/pre_money_valuation_currency_in_usd))+
  geom_boxplot(col = "red",
horizontal = TRUE,
notch = TRUE)+
  xlim(0,1)

relevant_for_funding_stages %>%
  filter(!is.na(pre_money_valuation_currency_in_usd))%>%
  filter(!is.na(total_funding_amount_currency_in_usd))%>%
  ggplot(aes(total_funding_amount_currency_in_usd/pre_money_valuation_currency_in_usd))+
  geom_boxplot(col = "red",
horizontal = TRUE,
notch = TRUE)+
  xlim(0,10)

relevant_for_funding_stages %>%
  filter(!is.na(pre_money_valuation_currency_in_usd))%>%
  filter(!is.na(total_funding_amount_currency_in_usd))%>%
  ggplot(aes(total_funding_amount_currency_in_usd/pre_money_valuation_currency_in_usd))+
  geom_boxplot(col = "red",
horizontal = TRUE,
notch = TRUE)+
  xlim(0,100)

relevant_for_funding_stages %>%
  filter(!is.na(pre_money_valuation_currency_in_usd))%>%
  filter(!is.na(money_raised_currency_in_usd))%>%
  ggplot(aes(money_raised_currency_in_usd/pre_money_valuation_currency_in_usd))+
  geom_boxplot(col = "red",
horizontal = TRUE,
notch = TRUE)+
  xlim(0,1)
```

```{r}
relevant_for_funding_stages %>%
  ggplot(aes(x = number_of_investors, y = total_funding_amount_currency_in_usd))+
  geom_point()
```


```{r}
relevant_for_funding_stages %>%
  select(money_raised_currency_in_usd, total_funding_amount_currency_in_usd, number_of_funding_rounds, transaction_name)%>%
  mutate(total_minus_money = total_funding_amount_currency_in_usd-money_raised_currency_in_usd)%>%
  filter(total_minus_money > 10)%>%
  arrange(transaction_name)
```





```{r}
relevant_for_funding_stages %>%
  select(transaction_name,money_raised_currency_in_usd, total_funding_amount_currency_in_usd, number_of_funding_rounds)%>%
  group_by(transaction_name)%>%
  summarise(count = n())%>%
  arrange(desc(count))

relevant_for_funding_stages %>%
  filter(transaction_name == "Funding Round - JewelStreet")
```


```{r}
startups_data %>%
  filter(funding_status == "M&A")%>%
  arrange(desc(total_funding_amount_currency_in_usd))
```

```{r}
startups_data %>%
  group_by(lead_investors)%>%
  summarise(sum = sum(total_funding_amount_currency_in_usd), number_of_investments = n())%>%
  arrange(desc(sum))
```







# Industry Analysis


```{r}
data = read.csv("startups_data.csv")

data = data %>% janitor::clean_names()
```

```{r}
skim(data)

data_clean = data %>% 
  select(-c("transaction_name_url", 
            "organization_name_url", 
            "money_raised_currency", 
            "total_funding_amount_currency", 
            "pre_money_valuation_currency", 
            "money_raised", 
            "total_funding_amount", 
            "pre_money_valuation"))

data_clean %>% count(organization_industries)

```

```{r}
data_clean = data_clean %>%
  mutate(industries = gsub("\\,.*,","", organization_industries))

data_clean = data_clean %>%
  mutate(industries = word(industries, 1, sep = " "), 
         industries = gsub(",","", industries), 
         root = wordStem(industries))
        
data_clean %>% 
  group_by(root) %>%
  summarize(Count=n()) %>%
  mutate(Percent = round((Count/sum(Count)*100))) %>%
  arrange(desc(Count))


industry_list = data_clean %>%
  group_by(root) %>%
  summarize(Count=n()) %>%
  mutate(Percent = round((Count/sum(Count)*100))) %>%
  filter(Percent > 1)

industry_list = industry_list$root

data_industry = data_clean %>%
  filter(root %in% industry_list) %>%
  drop_na(root)

data_industry = data_industry %>%
  mutate(three = substr(root, 1, 3))

data_industry %>% 
  group_by(three) %>%
  summarize(Count=n()) %>%
  mutate(Percent = round((Count/sum(Count)*100))) %>%
  arrange(desc(Count))

data_industry %>% 
  group_by(industries) %>%
  summarize(Count=n()) %>%
  mutate(Percent = round((Count/sum(Count)*100))) %>%
  arrange(desc(Count))

```

```{r}
data_industry %>%
  group_by(three) %>%
  summarize(Count=n()) %>%
  mutate(Percent = round((Count/sum(Count)*100))) %>%
  ggplot(aes(x = Percent, y = three, fill = three)) + 
  geom_col() +
  theme(legend.position = "none") +
  labs(title = "Distribution of Funding per Industry") +
  xlab("Percentage") +
  ylab("") 

data_industry = data_industry %>%
  mutate(year = substr(announced_date, 1, 4))

data_industry = data_industry %>%
  mutate(year_three = paste(year, three))

data_industry %>%
  group_by(three, year) %>%
  summarise(sum = sum(money_raised_currency_in_usd, na.rm = TRUE)) %>%
  ggplot() +
  geom_point(aes(x = year, y = sum, color = three)) +
  geom_line(aes(x = year, y = sum, color = three, group = 1)) +
  facet_wrap(~three) +
  NULL

data_industry %>%
  group_by(three, year) %>%
  summarise(count = n()) %>%
  ggplot() +
  geom_point(aes(x = year, y = count, color = three)) +
  geom_line(aes(x = year, y = count, color = three, group = 1)) +
  facet_wrap(~three) +
  NULL

data_industry %>%
  group_by(three, year) %>%
  summarise(count = n(), 
            sum = sum(money_raised_currency_in_usd, na.rm = TRUE), 
            avg_deal = sum/count) %>%
  ggplot() +
  geom_point(aes(x = year, y = avg_deal, color = three)) +
  geom_line(aes(x = year, y = avg_deal, color = three, group = 1)) +
  facet_wrap(~three) +
  NULL

```


# Wordcloud

```{r}
data_startups_original <- "STARTUPS"
files <- fs::dir_ls(path = data_startups_original, regexp = "\\.csv$", recurse = TRUE) 
startups_data <- vroom(files, id = "source")
write.csv(x = startups_data,file = "startups_data.csv")

```

```{r}
startups_data <- startups_data %>% clean_names()
skim(startups_data)

startups_data_year_2017<-startups_data %>% 
   filter(announced_date >= as.Date("2016-01-01") & announced_date <= as.Date("2018-01-01"))

startups_data_year_2018<-startups_data %>% 
   filter(announced_date >= as.Date("2018-01-01") & announced_date <= as.Date("2019-01-01"))

startups_data_year_2019<-startups_data %>% 
   filter(announced_date >= as.Date("2019-01-01") & announced_date <= as.Date("2020-01-01"))

startups_data_year_2020<-startups_data %>% 
   filter(announced_date >= as.Date("2020-01-01") & announced_date <= as.Date("2021-01-01"))

startups_data_year_2021<-startups_data %>% 
   filter(announced_date >= as.Date("2021-01-01") & announced_date <= as.Date("2022-01-01"))

```

```{r}
startups_data_text1<- startups_data_year_2017 %>% 
  select(organization_industries)
  paste(unlist(startups_data_text1), collapse =" ")
  
write.table(startups_data_text1, file = "startups_data_2017.text", sep = "\t",
            row.names = FALSE)
            
#source('http://www.sthda.com/upload/rquery_wordcloud.r')
startups_data_text2<- startups_data_year_2021 %>% 
  select(organization_industries)
  paste(unlist(startups_data_text2), collapse =" ")
  
write.table(startups_data_text2, file = "startups_data_2021.text", sep = "\t",
            row.names = FALSE)
            
#source('http://www.sthda.com/upload/rquery_wordcloud.r')

```

```{r}
#source('http://www.sthda.com/upload/rquery_wordcloud.r')
#filePath <- "startups_data.text"
#res<-rquery.wordcloud(filePath, type ="file", lang = "english",excludeWords="company", min.freq = 1,  max.words = 150)

filePath1 <- "startups_data_2017.text"
res<-rquery.wordcloud(filePath1, type ="file", lang = "english",excludeWords=c("company","CSV"), min.freq = 1,  max.words =150)


```






Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
filePath2 <- "startups_data_2021.text"
res<-rquery.wordcloud(filePath2, type ="file", lang = "english",excludeWords=c("company","CSV"), min.freq = 1,  max.words =150)

```




# Map Visualisations

```{r}
#data_startups_original <- "STARTUPS"
#files <- fs::dir_ls(path = data_startups_original, regexp = "\\.csv$", recurse = TRUE) 
#startups_data <- vroom(files, id = "source")
#write.csv(x = startups_data,file = "startups_data.csv")

#data_investors_original <- "INVESTORS"
#files <- fs::dir_ls(path = data_investors_original, regexp = "\\.csv$", recurse = TRUE) 
#investors_data <- vroom(files, id = "source")
#write.csv(x = investors_data,file = "investors_data.csv")

startups_data <- read.csv("startups_data.csv")
investors_data <- read.csv("investors_data.csv")
```

```{r}
names(startups_data)[names(startups_data) == 'Organization.Location'] <- 'location'
names(startups_data)[names(startups_data) == 'Announced.Date'] <- 'date'
startups_data
```


```{r}
startups_data <- startups_data %>%
  mutate(year = year(date))
```

```{r warning = FALSE}
location_counts <- startups_data %>% 
  group_by(location) %>% 
  tally() %>%
  separate(location, c('location', 'shire', 'country','continent')) %>%
  select(-shire, -country, -continent)

location_counts2017 <- startups_data %>% 
  filter(year == 2017) %>% 
  group_by(location) %>% 
  tally() %>%
  separate(location, c('location', 'shire', 'country','continent')) %>%
  select(-shire, -country, -continent)

location_counts2018 <- startups_data %>% 
  filter(year == 2018) %>% 
  group_by(location) %>% 
  tally() %>%
  separate(location, c('location', 'shire', 'country','continent')) %>%
  select(-shire, -country, -continent)

location_counts2019 <- startups_data %>% 
  filter(year == 2019) %>% 
  group_by(location) %>% 
  tally() %>%
  separate(location, c('location', 'shire', 'country','continent')) %>%
  select(-shire, -country, -continent)

location_counts2020 <- startups_data %>% 
  filter(year == 2020) %>% 
  group_by(location) %>% 
  tally() %>%
  separate(location, c('location', 'shire', 'country','continent')) %>%
  select(-shire, -country, -continent)

location_counts2021 <- startups_data %>% 
  filter(year == 2021) %>% 
  group_by(location) %>% 
  tally() %>%
  separate(location, c('location', 'shire', 'country','continent')) %>%
  select(-shire, -country, -continent)

location_counts
location_counts2017
location_counts2018
location_counts2019
location_counts2020
location_counts2021
```
# method 1: github open source location information

```{r}
geocorrected <- read_csv('https://raw.githubusercontent.com/networkingarchives/networkingarchives.github.io/main/geocorrected.csv')
colnames(geocorrected)[7:9] = c('wikititle', 
                                'lat', 
                                'lng')

geocorrected <- geocorrected %>% 
  select(-1, -10,-11, -12) %>%
  select(-General.area.of.coverage, -Country.of.publication, -places)

names(geocorrected)[names(geocorrected) == 'Coverage..City'] <- 'location'
names(geocorrected)[names(geocorrected) == 'lng'] <- 'long'

geocorrected <- geocorrected %>%
  mutate(lat = as.numeric(lat)) %>% 
  mutate(lng = as.numeric(long)) %>% 
  filter(!is.na(lat)) %>% 
  filter(!is.na(long))

geocorrected
```
```{r}
final_map <- left_join(geocorrected, location_counts)
final_map <-  final_map %>%
              select(-wikititle, -status) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
final_map
```

```{r fig.width = 5, warning = FALSE}
worldmap = map_data('world')
ggplot() + 
  geom_polygon(data = worldmap, 
               aes(x = long, y = lat, group = group), 
               fill = '#f3f3f3', 
               color = 'black') + 
  coord_fixed(ratio = 1.3, xlim = c(-10,3), ylim = c(50, 59)) + 
  theme(panel.background = element_rect(fill = "grey90")) +
  geom_point(data = final_map, 
             aes(x = as.numeric(lng), 
                 y = as.numeric(lat), size = n, color = log(n)), alpha = 0.6) + 
  scale_size_area(max_size = 12) + 
  scale_color_viridis_c() + 
  theme(legend.position = 'B') + 
  labs (title = "The Location Distribution of Start-ups in U.K. in the Past 5 Years",
        subtitle = "Apart from London, which city is heaven for start-ups") +
  NULL
```

# method 2: ggplot package source

```{r}
UK <- map_data("world") %>% filter(region=="UK")
citydata <- world.cities %>%
  filter(country.etc=="UK") %>%
  mutate(location = name)
```

```{r}
final_map2 <- left_join(citydata,location_counts)
final_map2 <- final_map2 %>%
              select(-name, -country.etc, -pop, -capital) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
final_map2
```


```{r}
final_map2 %>%
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2, aes(x = long, y = lat), color = "#000080") +
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  labs (title = "The Start-ups map in U.K. for past 5 years") +
  NULL
```

```{r}
final_map2017 <- left_join(citydata,location_counts2017) %>%
              select(-name, -country.etc, -pop, -capital) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
final_map2018 <- left_join(citydata,location_counts2018) %>%
              select(-name, -country.etc, -pop, -capital) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
final_map2019 <- left_join(citydata,location_counts2019) %>%
              select(-name, -country.etc, -pop, -capital) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
final_map2020 <- left_join(citydata,location_counts2020) %>%
              select(-name, -country.etc, -pop, -capital) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
final_map2021 <- left_join(citydata,location_counts2021) %>%
              select(-name, -country.etc, -pop, -capital) %>%
              filter(!is.na(n)) %>%
              arrange(desc(n))
```

```{r}
library(gridExtra)
map2017 <- final_map2017 %>%
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2017, aes(x = long, y = lat), color = "#000080") +
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  ggtitle("2017")

map2018 <- final_map2018 %>%
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2018, aes(x = long, y = lat), color = "#000080") +
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  ggtitle("2018")

map2019 <- final_map2019 %>%
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2019, aes(x = long, y = lat), color = "#000080") +
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  ggtitle("2019")

map2020 <- final_map2020 %>%
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2020, aes(x = long, y = lat), color = "#000080") +
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  ggtitle("2020")

map2021 <- final_map2021 %>%
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2021, aes(x = long, y = lat), color = "#000080") +
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  ggtitle("2021")

map2017
map2018
map2019
map2020
map2021
```

```{r}
# save each map as png
ggsave('map2017.jpeg', plot = map2017, device = NULL,width = 6, height = 6, units = 'in')
ggsave('map2018.jpeg', plot = map2018, device = NULL,width = 6, height = 6, units = 'in')
ggsave('map2019.jpeg', plot = map2019, device = NULL,width = 6, height = 6, units = 'in')
ggsave('map2020.jpeg', plot = map2020, device = NULL,width = 6, height = 6, units = 'in')
ggsave('map2021.jpeg', plot = map2021, device = NULL,width = 6, height = 6, units = 'in')
```


```{r}
# create gif
library(magick)
list.files(pattern = '*.jpeg', full.names = TRUE) %>% 
        image_read() %>% # reads each path file
        image_join() %>% # join images
        image_animate(fps=4) %>% # animates, opt for number of loops
        image_write("location change.gif") # save to current folder
```


```{r}
library(ggrepel)
ggplot() +
  geom_polygon(data = UK, aes(x = long, y = lat, group = group),
               fill = "grey", alpha=0.3) +
  geom_point(data = final_map2, aes(x = long, y = lat, alpha = log(n))) +
  geom_text_repel(data = final_map2 %>% 
#                 arrange(desc(n)) %>% 
                    head(10),
                    aes(x = long, y = lat, label = location), size = 3) +
  geom_point(data = final_map2 %>% 
#             arrange(desc(n)) %>% 
               head(10),
             aes(x = long, y = lat), color="#b22222", size=4) + 
  theme_void() +
  ylim(50, 59) +
  coord_map() +
  theme(legend.position = "none") +
  labs (title = "Top 10 cities for start-ups in U.K. for past 5 years") +
  NULL
```

```{r}
library(viridis)
final_map2 %>%
  arrange(desc(n)) %>%
  mutate(location=factor(location,unique(location))) %>%
  ggplot() +
  geom_polygon(data = UK, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point( aes(x=long, y=lat, size=n, color=n), alpha=0.9) +
  scale_size_continuous(range=c(1,12)) +
  scale_color_viridis(trans="log") +
  theme_void() + 
  ylim(50,59) + 
  coord_map() + 
  theme(legend.position="none") + 
  labs (title = "The Location Distribution of Start-ups in U.K. ",
        subtitle = "Apart from London, which city is heaven for start-ups") +
  NULL
```

```{r}
# bubble map for start-ups
mybreaks <- c(0.02, 0.04, 0.08, 1, 7)
final_map2 <- final_map2 %>%
  arrange(desc(n)) %>%
  mutate(location=factor(location, unique(location))) 

final_map2 %>%
  ggplot() +
  geom_polygon(data = UK, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(aes(x=long, y=lat, size=n, color=n, alpha=n), shape=20, stroke=FALSE) +
  scale_size_continuous( range=c(1,12), breaks=mybreaks) +
  scale_alpha_continuous( range=c(0.1, .9), breaks=mybreaks) +
  scale_color_viridis(option="magma", breaks=mybreaks) +
  theme_void() + 
  ylim(50,59) + 
  coord_map() + 
  theme(legend.position = "none") +
  labs (title = "The Location Distribution of Start-ups in U.K. ",
        subtitle = "Apart from London, which city is heaven for start-ups") +
  NULL
```

```{r}
# interactive map
# Load the plotly package
library(plotly)

# Reorder data + Add a new column with tooltip text
final_map2 <- final_map2 %>%
  arrange(desc(n)) %>%
  mutate(location=factor(location, unique(location)))  %>%
  mutate(mytext = paste(
    "City:",location,"\n","Number of Start-ups:", n, sep = ""
  ))

# Make the map (static)
p <- final_map2 %>%
  ggplot() + 
  geom_polygon(data = UK, aes(x=long, y = lat, group = group),fill = "grey", alpha=0.3) +
  geom_point(aes(x=long, y=lat, size=n, color=n, text=mytext, alpha=n) ) +
  scale_size_continuous(range=c(1,15)) +
  scale_color_viridis(option="inferno", trans="log" ) +
  scale_alpha_continuous(trans="log") +
  theme_void() +
  ylim(50,59) +
  coord_map() +
  theme(legend.position = "none") +
  NULL

p <- ggplotly(p, tooltip="text")
p
```

# investors

```{r}
names(investors_data)[names(investors_data) == 'Location'] <- 'location'
investors_data
```

```{r warning = FALSE}
library(countrycode)
investor_location_counts <- investors_data %>% 
  separate(location, c('city','state','country'), sep = ",") %>%
  select(-city,-state)
  
investor_location_counts$country_code <- countrycode(sourcevar = investor_location_counts$country,
                                         origin = "country.name",
                                         destination = "iso3c")
investor_location_counts <- investor_location_counts %>% 
                            group_by(country_code) %>%
                            tally() %>%
                            drop_na()
  
investor_location_counts
```

```{r warning=FALSE}
map_world <- map_data("world")

map_world$country_code <- countrycode(sourcevar = map_world$region,
                          origin = "country.name",
                          destination = "iso3c")

final_map_world <- left_join(map_world, investor_location_counts, by = "country_code")
```

```{r fig.width = 10}
ggplot(final_map_world, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = n), color = "white") +
  labs(title = "start-up investors map in past 5 years ") +
       xlab ("longitude") +
       ylab ("latitude") +
  scale_fill_viridis_c(option = "C", name ="number of investors") +
  theme_bw() 
```

```{r}
library(plotly)

# Reorder data + Add a new column with tooltip text
final_map_world <- final_map_world %>%
  arrange(desc(n)) %>%
  mutate(mytext = paste(
    "Country:",country_code,"\n","Number of investors:", n, sep = ""
  ))

# Make the map (static)
w <- ggplot(final_map_world, aes(x = long, y = lat,text=mytext, group = group)) +
  geom_polygon(aes(fill = n), color = "white") +
  labs(title = "start-up investors map in past 5 years ") +
       xlab ("longitude") +
       ylab ("latitude") +
  scale_fill_viridis_c(option = "C", name ="number of investors") +
  theme_bw() +
  NULL

w <- ggplotly(w, tooltip="text")
w
```







